/* #START SERVICES */

export const USER_SERVICE = 'USER_SERVICE'

export const DISCORD_AUTH_SERVICE = 'DISCORD_AUTH_SERVICE'

export const LOCAL_AUTH_SERVICE = 'LOCAL_AUTH_SERVICE'

export const PRISMA_SERVICE = 'PRISMA_SERVICE'

export const DISCORD_USER_SERVICE = 'DISCORD_USER_SERVICE'

export const VENDOR_SERVICE = 'VENDOR_SERVICE'

export const SNOWFLAKE_SERVICE = 'SNOWFLAKE_SERVICE'

export const IMAGE_SERVICE = 'IMAGE_SERVICE'

export const DESIGNER_SERVICE = 'DESIGNER_SERVICE'

export const PRODUCT_SERVICE = 'PRODUCT_SERVICE'

export const FORM_SERVICE = 'FORM_SERVICE'

/* #END SERVICES */

export const REDIS = 'REDIS'
