/* #START SERVICES */

export const USERS_SERVICE = 'USERS_SERVICE'

export const DISCORD_AUTH_SERVICE = 'DISCORD_AUTH_SERVICE'

export const LOCAL_AUTH_SERVICE = 'LOCAL_AUTH_SERVICE'

export const PRISMA_SERVICE = 'PRISMA_SERVICE'

export const DISCORD_USERS_SERVICE = 'DISCORD_USERS_SERVICE'

export const KEYCAPS_SERVICE = 'KEYCAPS_SERVICE'

export const VENDORS_SERVICE = 'VENDORS_SERVICE'

export const REDDIT_USERS_SERVICE = 'REDDIT_USERS_SERVICE'

export const REDDIT_AUTH_SERVICE = 'REDDIT_AUTH_SERVICE'

/* #END SERVICES */

export const REDIS = 'REDIS'
